require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'reactnativecli' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'RNMetronome', :path => '../node_modules/react-native-metronome'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  target 'reactnativecliTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'reactnativecli-tvOS' do
  # Pods for reactnativecli-tvOS

  target 'reactnativecli-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
